In [2]:
import numpy as np

## Списочная индексация

In [4]:
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
b = a[[1, 2, -1, -1, -1]] # копия по индексам
print(b)
b[1] = 77
print(a)
print(b)

[11 12 19 19 19]
[10 11 12 13 14 15 16 17 18 19]
[11 77 19 19 19]


In [10]:
a > 13

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [11]:
a[a > 13]

array([14, 15, 16, 17, 18, 19])

In [12]:
a[np.logical_and(a >= 12, a <= 18)]

array([12, 13, 14, 15, 16, 17, 18])

In [15]:
print(a)
a[a > 13] = -1
print(a)
a[[1, 3, 6]] = 0
print(a)

[10  0 12  0 -1 -1  0 -1 -1 -1]
[10  0 12  0 -1 -1  0 -1 -1 -1]
[10  0 12  0 -1 -1  0 -1 -1 -1]


## Индексы в многомерных массивах

In [17]:
m = np.arange(3 * 2 * 4)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [19]:
m = m.reshape(3, 2, 4)
m

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [20]:
m[1]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
m[1, 1]

array([12, 13, 14, 15])

In [24]:
m[1, 1, 1]

13

## Срезы в многомерных массивах

In [25]:
m

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [28]:
m[1:]

array([[[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [32]:
m[:,0,:]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [33]:
m[:,0,-1:]

array([[ 3],
       [11],
       [19]])

In [34]:
m[:,0,-1:] = -1
m

array([[[ 0,  1,  2, -1],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, -1],
        [12, 13, 14, 15]],

       [[16, 17, 18, -1],
        [20, 21, 22, 23]]])

## Списочная индексация в многомерных массивах

In [36]:
m = np.arange(3 * 3).reshape(3, 3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
m[[1, 0, -1]]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [42]:
indexes = np.array([
    [0, 1],
    [-1,-2]
])
m[indexes]

array([[[0, 1, 2],
        [3, 4, 5]],

       [[6, 7, 8],
        [3, 4, 5]]])

In [44]:
m[0] = -1
m

array([[-1, -1, -1],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [45]:
m[1] += 100
m

array([[ -1,  -1,  -1],
       [103, 104, 105],
       [  6,   7,   8]])