# Линейная алгебра с NumPy

In [60]:
import numpy as np

In [61]:
np.__version__

'1.20.1'

## Вектор



In [89]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])

In [63]:
a.dtype

dtype('int32')

In [64]:
c = np.array([5,6,7,8],dtype=float)
c.dtype

dtype('float64')

In [90]:
a + b

array([15, 23, 14,  8])

In [91]:
a - b

array([ 5, -7, -4, -6])

In [92]:
a * 2

array([20, 16, 10,  2])

## Матрица

In [94]:
d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [96]:
d.shape

(4, 3)

In [97]:
print(f"{d[0,0]=}")
print(f"{d[1,2]=}")
print(f"{d[2,1]=}")

d[0,0]=1
d[1,2]=6
d[2,1]=8


In [101]:
m1 = np.matrix("1,2;3,4;5,6")
m1

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [102]:
m2 = np.matrix("-1,-3;9,7;-5,8")
m2

matrix([[-1, -3],
        [ 9,  7],
        [-5,  8]])

In [103]:
m1 + m2

matrix([[ 0, -1],
        [12, 11],
        [ 0, 14]])

In [104]:
m1 * 100

matrix([[100, 200],
        [300, 400],
        [500, 600]])

In [105]:
m1.T

matrix([[1, 3, 5],
        [2, 4, 6]])

In [108]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [109]:
#(1)
arr_sum = 0
for i in range(len(arr)):
    arr_sum += arr[i]
arr_sum

10

In [110]:
#(2)
arr_sum = 0
for i in arr:
    arr_sum += i
arr_sum

10

In [111]:
#(3)
arr_sum = arr.sum()
print(arr_sum)

10


In [113]:
arr = np.array([1,-2,3,-4])
print(f"{np.abs(arr)=}")
print(f"{np.sqrt(arr)=}")
print(f"{np.modf(arr)=}")

np.abs(arr)=array([1, 2, 3, 4])
np.sqrt(arr)=array([1.        ,        nan, 1.73205081,        nan])
np.modf(arr)=(array([ 0., -0.,  0., -0.]), array([ 1., -2.,  3., -4.]))


C:\Users\Admin\AppData\Local\Temp\ipykernel_18676\2533317530.py:3: RuntimeWarning: invalid value encountered in sqrt
  print(f"{np.sqrt(arr)=}")


In [115]:
a = [x for x in range(1,10)]
b = [x**2 for x in range(1,10)]
c = [x**3 for x in range(1,10)]

m = np.array([a,b,c])
m

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81],
       [  1,   8,  27,  64, 125, 216, 343, 512, 729]])

## Индексы

In [116]:
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [117]:
print(a[1])
print(a[-1])

11
19


In [118]:
a[1] = -1
a

array([10, -1, 12, 13, 14, 15, 16, 17, 18, 19])

In [122]:
b = a[1:4] # создается представление, а НЕ копия
b[1] = -5
print(a)
print(b)

[10 -1 -5 13 14 15 16 17 18 19]
[-1 -5 13]


In [124]:
a[3:7] = 0
print(a)
a[::2] = -99
print(a)

[10 -1 -5  0  0  0  0 17 18 19]
[-99  -1 -99   0 -99   0 -99  17 -99  19]


## Списочная индексация

In [67]:
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [68]:
b = a[[1, 2, -1, -1, -1]] # копия по индексам
print(b)
b[1] = 77
print(a)
print(b)

[11 12 19 19 19]
[10 11 12 13 14 15 16 17 18 19]
[11 77 19 19 19]


In [69]:
a > 13

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [70]:
a[a > 13]

array([14, 15, 16, 17, 18, 19])

In [71]:
a[np.logical_and(a >= 12, a <= 18)]

array([12, 13, 14, 15, 16, 17, 18])

In [72]:
print(a)
a[a > 13] = -1
print(a)
a[[1, 3, 6]] = 0
print(a)

[10 11 12 13 14 15 16 17 18 19]
[10 11 12 13 -1 -1 -1 -1 -1 -1]
[10  0 12  0 -1 -1  0 -1 -1 -1]


## Индексы в многомерных массивах

In [73]:
m = np.arange(3 * 2 * 4)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [74]:
m = m.reshape(3, 2, 4)
m

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [75]:
m[1]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [76]:
m[1, 1]

array([12, 13, 14, 15])

In [77]:
m[1, 1, 1]

13

## Срезы в многомерных массивах

In [78]:
m

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [79]:
m[1:]

array([[[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [80]:
m[:,0,:]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [81]:
m[:,0,-1:]

array([[ 3],
       [11],
       [19]])

In [82]:
m[:,0,-1:] = -1
m

array([[[ 0,  1,  2, -1],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, -1],
        [12, 13, 14, 15]],

       [[16, 17, 18, -1],
        [20, 21, 22, 23]]])

## Списочная индексация в многомерных массивах

In [83]:
m = np.arange(3 * 3).reshape(3, 3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [84]:
m[[1, 0, -1]]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [85]:
indexes = np.array([
    [0, 1],
    [-1,-2]
])
m[indexes]

array([[[0, 1, 2],
        [3, 4, 5]],

       [[6, 7, 8],
        [3, 4, 5]]])

In [86]:
m[0] = -1
m

array([[-1, -1, -1],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [87]:
m[1] += 100
m

array([[ -1,  -1,  -1],
       [103, 104, 105],
       [  6,   7,   8]])