# Случайные числа в NumPy

In [2]:
import numpy as np

In [4]:
# [начало; конец)
np.random.randint(5)

3

In [5]:
np.random.randint(1,10,5)

array([5, 4, 4, 8, 9])

In [6]:
np.random.randint(1, 10, (2,3))

array([[5, 3, 9],
       [4, 1, 2]])

In [7]:
np.random.randint(1, 10, size=(4,4))

array([[4, 9, 2, 3],
       [9, 8, 1, 8],
       [4, 2, 6, 4],
       [2, 4, 6, 4]])

In [12]:
np.random.choice(2, 5)

array([0, 1, 1, 0, 1])

In [13]:
# Вернуть массив уникальных элементов
np.random.choice(10, 10, replace=False)

array([8, 5, 0, 7, 3, 6, 2, 1, 4, 9])

In [16]:
a = np.arange(10)
np.random.choice(a, size=(2,4))

array([[2, 1, 9, 2],
       [3, 5, 9, 6]])

In [17]:
weather = ['Солнечно', 'Пасмурно', 'Дождливо', 'Ветрено']
perm = [0.1, 0.5, 0.3, 0.1]
np.random.choice(weather, size=7, p=perm)

array(['Пасмурно', 'Дождливо', 'Ветрено', 'Дождливо', 'Пасмурно',
       'Пасмурно', 'Пасмурно'], dtype='<U8')

In [27]:
np.random.rand(5)

array([0.24049131, 0.10702067, 0.35027364, 0.19006583, 0.63101262])

In [28]:
np.random.rand(2,4)

array([[0.37749452, 0.83371479, 0.3081111 , 0.35357723],
       [0.46051441, 0.48908842, 0.7599006 , 0.78075883]])

In [29]:
np.random.uniform(1, 10, 5)

array([4.55335744, 9.02821006, 7.73637832, 4.26521516, 2.80801517])

In [30]:
a = [1, 2, 3, 4, 5]
np.random.shuffle(a)
a

[3, 4, 5, 2, 1]

In [31]:
a = np.arange(10)
np.random.shuffle(a)
a

array([9, 3, 8, 2, 6, 0, 7, 5, 1, 4])

In [33]:
a = np.arange(15).reshape(3,5)
np.random.shuffle(a[0])
a

array([[ 1,  4,  3,  0,  2],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])